services:
  - type: web
    name: diabetes-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn prediction:app --host 0.0.0.0 --port 8080
    workingDir: summative/API
    envVars:
      - key: PYTHON_VERSION
        value: "3.10"
