// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC96gb_1AlOZKSWRZR89_UDPDeaZ-M4IlE',
    appId: '1:211252752531:web:a9c674223c7184cc135d66',
    messagingSenderId: '211252752531',
    projectId: 'eclinic-91106',
    authDomain: 'eclinic-91106.firebaseapp.com',
    storageBucket: 'eclinic-91106.firebasestorage.app',
    measurementId: 'G-4D7BH7TNZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFuJpanB8AUsvPPnyflPJqKT8VtPJEo5c',
    appId: '1:211252752531:android:ae3dd4a3d5238b1f135d66',
    messagingSenderId: '211252752531',
    projectId: 'eclinic-91106',
    storageBucket: 'eclinic-91106.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA-UaIYKFJsWVoO0MaPV0-lZnigll0AQk',
    appId: '1:211252752531:ios:f18d438498c170c6135d66',
    messagingSenderId: '211252752531',
    projectId: 'eclinic-91106',
    storageBucket: 'eclinic-91106.firebasestorage.app',
    iosBundleId: 'com.example.eClinic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA-UaIYKFJsWVoO0MaPV0-lZnigll0AQk',
    appId: '1:211252752531:ios:f18d438498c170c6135d66',
    messagingSenderId: '211252752531',
    projectId: 'eclinic-91106',
    storageBucket: 'eclinic-91106.firebasestorage.app',
    iosBundleId: 'com.example.eClinic',
  );
}
